# Generated by Django 4.2.11 on 2025-10-15 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_hours', to='staff.weeklyschedule')),
            ],
        ),
        migrations.RemoveField(
            model_name='activity',
            name='timetables',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='timetable',
        ),
        migrations.AddField(
            model_name='reservation',
            name='end_time',
            field=models.TimeField(default='11:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_time',
            field=models.TimeField(default='12:00'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TimeTable',
        ),
    ]
